# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            "Clayton's blog"
tagline:          
description:      'Thoughts, projects, and anything, really...'
url:              https://claytonyoung.github.io/
baseurl:          https://claytonyoung.github.io/

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:     https://github.com/ClaytonYoung/ClaytonYoung.github.io
  repo:     https://github.com/ClaytonYoung/ClaytonYoung.github.io      
