# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            "Clayton’s Blog"
tagline:          
description:      'Thoughts, projects, and anything, really...'
url:              https://claytonyoung.github.io/
baseurl:          https://claytonyoung.github.io/

author: Clayton Young
  name:           
  url:            

paginate:         5

include:
  - .htaccess
  - _pages
  - _articles
  - _data

# Custom vars
version:          2.1.0

github: https://github.com/ClaytonYoung/ClaytonYoung.github.io/tree/master/projects
  repo: https://github.com/ClaytonYoung/ClaytonYoung.github.io/tree/master/projects
  
  social-network-links:
  email: "jcyoung91@gmail.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: ClaytonYoung
