# Dependencies
markdown:         redcarpet
highlighter:      pygments
<<<<<<< HEAD

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title: Clayton's blog
tagline: Data, science, and other thoughts
url: 
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed
