# Permalinks
permalink:           pretty

# Setup
title:               Clayton Young
tagline:             A blog..?
url:                 http://ClaytonYoung.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Clayton Young
  email:             jcyoung91@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ClaytonYoung

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
