# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            C L A Y
tagline:          
description:      'thoughts, projects, and anything, really...'
url:              https://claytonyoung.github.io/
baseurl:          https://claytonyoung.github.io/

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
